"""add video_prompt to clips

Revision ID: 345e71e54166
Revises: 2947e322f588
Create Date: 2026-09-22 00:08:39.739117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '345e71e54166'
down_revision: Union[str, None] = '2947e322f588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('video_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clips', 'video_prompt')
    # ### end Alembic commands ###
