"""add video_asset_id to clips

Revision ID: 55aee7356be3
Revises: 345e71e54166
Create Date: 2026-09-22 00:36:40.245691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55aee7356be3'
down_revision: Union[str, None] = '345e71e54166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clips', sa.Column('video_asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_clips_video_asset_id', 'clips', 'assets', ['video_asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_clips_video_asset_id', 'clips', type_='foreignkey')
    op.drop_column('clips', 'video_asset_id')
    # ### end Alembic commands ###
