"""create master_themes table

Revision ID: 83a8b82a602c
Revises: 
Create Date: 2026-09-21 19:52:11.539499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83a8b82a602c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_themes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('concept', sa.Text(), nullable=False),
    sa.Column('character_json', sa.JSON(), nullable=True),
    sa.Column('environment_json', sa.JSON(), nullable=True),
    sa.Column('visual_style_json', sa.JSON(), nullable=True),
    sa.Column('animation_rules_json', sa.JSON(), nullable=True),
    sa.Column('music_style_json', sa.JSON(), nullable=True),
    sa.Column('reference_image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_themes')
    # ### end Alembic commands ###
