"""create projects table

Revision ID: f1f74eee0eb8
Revises: 83a8b82a602c
Create Date: 2026-09-21 20:30:08.277109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1f74eee0eb8'
down_revision: Union[str, None] = '83a8b82a602c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_theme_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('clip_count', sa.Integer(), nullable=False),
    sa.Column('music_count', sa.Integer(), nullable=False),
    sa.Column('target_duration', sa.Integer(), nullable=False),
    sa.Column('image_provider', sa.String(length=50), nullable=False),
    sa.Column('video_provider', sa.String(length=50), nullable=False),
    sa.Column('music_provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['master_theme_id'], ['master_themes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
